name: Bump Version & Push Tag
on:
  push:
    branches:
      - main
    paths:
      - "**.go"

jobs:
  bump-push-tag:
    name: Bump Version & Push Tag
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Bump Version & Push Tag
        id: bump-tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          DEFAULT_BUMP: minor
          RELEASE_BRANCHES: main
          TAG_CONTEXT: repo
          WITH_V: true
