name: Update Go Install Cache (Main)

on:
  push:
    branches:
      - main

jobs:
  go-install-cache:
    name: Update Go Install Cache (Main)
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "./go.mod"

      - name: Cache Go Installs
        id: cache-go-installs
        uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-installs

      - name: Install Go Dependencies
        if: steps.cache-go-installs.outputs.cache-hit != 'true'
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
